name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Show Xcode Version
        run: xcode-select -p

      - name: Show Build Settings
        run: xcodebuild -showBuildSettings

      - name: Show Build SDK
        run: xcodebuild -showsdks

      - name: Show Available Destinations
        run: xcodebuild -workspace DocumentScanner.xcodeproj/project.xcworkspace -scheme DocumentScanner -showdestinations

      - name: Build
        run: xcodebuild clean build -project DocumentScanner.xcodeproj -scheme DocumentScanner CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO

      - name: Tests
        run: xcodebuild clean test -project DocumentScanner.xcodeproj -scheme DocumentScannerTests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO

  semantic-release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Semantic Release
        run: |
          sudo npm i -g \
            semantic-release@19.0.2 \
            @semantic-release/git@10.0.1

      - name: Generate Token
        id: generate_token
        uses: tibdex/github-app-token@v1.5.2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Release
        run: semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}